Changed energies parameter in cmd line. Added check of command failure at each step of the script

diff --git a/nafhh/calibration/run-soft-comp-calibration b/nafhh/calibration/run-soft-comp-calibration
--- a/nafhh/calibration/run-soft-comp-calibration
+++ b/nafhh/calibration/run-soft-comp-calibration
@@ -94,7 +94,12 @@ for energy in ${softCompEnergies}
 do
   hadd \
   SoftwareCompensation-s${ilcsoft}-G${detector}-Pkaon0L-E${energy}-ILDCalibration_combined.root \
-  /nfs/dust/ilc/group/ild/calibration/calibration/SoftwareCompensation-s${ilcsoft}-G${detector}-Pkaon0L-E${energy}-ILDCalibration_*.root  
+  /nfs/dust/ilc/group/ild/calibration/calibration/SoftwareCompensation-s${ilcsoft}-G${detector}-Pkaon0L-E${energy}-ILDCalibration_*.root
+
+  if [ $? -ne 0 ]; then
+      echo "Failed to combine root files !"
+      exit 1
+  fi
 done
 
 # Run calibration scripts
@@ -103,17 +108,27 @@ python ${LCCalibration_DIR}/scripts/run-ild-calibration.py \
   --inputCalibrationFile ${calibrationFile} \
   --compactFile ${compactFile} \
   --steeringFile ${inputSteeringFile} \
-  --energies ${softCompEnergies} \
+  --energies 10 20 30 40 50 60 70 80 90 \
   --rootFilePattern ${softCompRootFiles} \
   --runMinimizer \
   --energies ${energies} \
   --startStep 6 \
   --endStep 6
 
+if [ $? -ne 0 ]; then
+    echo "Failed to run software compensation minimizer !"
+    exit 1
+fi
+
 # Replace SC weights in Marlin steering file
 python ${LCCalibration_DIR}/scripts/replace-marlin-parameters.py \
   --steeringFile ${inputSteeringFile} \
   --inputFile ${calibrationFile}
+
+if [ $? -ne 0 ]; then
+    echo "Failed to replace software compensation weights in the Marlin steering file !"
+    exit 1
+fi
 
 ########################################
 # Save output files for further analysis
