Added check on command result before copying output files

diff --git a/nafhh/calibration/run-calibration b/nafhh/calibration/run-calibration
--- a/nafhh/calibration/run-calibration
+++ b/nafhh/calibration/run-calibration
@@ -106,6 +106,11 @@ python ${LCCalibration_DIR}/scripts/extract-marlin-parameters.py \
   --steeringFile bbudsc_3evt_stdreco_dd4hep.xml \
   --outputFile ${calibrationFile}
 
+if [ $? -ne 0 ]; then
+    echo "Failed to extract calibration parameters from Marlin steering file !"
+    exit 1
+fi
+
 # Run calibration
 python ${LCCalibration_DIR}/scripts/run-ild-calibration.py \
   --inputCalibrationFile ${calibrationFile} \
@@ -118,10 +123,20 @@ python ${LCCalibration_DIR}/scripts/run-ild-calibration.py \
   --lcioKaon0LFile ${kaon0LFile} \
   --endStep 5
 
+if [ $? -ne 0 ]; then
+    echo "Failed to run calibration !"
+    exit 1
+fi
+
 python ${LCCalibration_DIR}/scripts/replace-marlin-parameters.py \
   --steeringFile bbudsc_3evt_stdreco_dd4hep.xml \
   --inputFile ${calibrationFile} \
   --newSteeringFile ${outputDirectory}/${outputSteeringFile}
+
+if [ $? -ne 0 ]; then
+    echo "Failed to replace calibration parameters in Marlin steering file !"
+    exit 1
+fi
 
 ########################################
 # Save output files for further analysis
